"""separate_access_type_pricing

Revision ID: 548d52b4d03d
Revises: 45f685eb08de
Create Date: 2026-04-25 00:09:15.355817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548d52b4d03d'
down_revision: Union[str, Sequence[str], None] = '45f685eb08de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'reversion_snapshot',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='reversion_snapshot::json')
    op.add_column('pricing_configs', sa.Column('timeslot_daily_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('timeslot_weekly_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('timeslot_monthly_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('anytime_daily_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('anytime_weekly_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('anytime_monthly_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.drop_column('pricing_configs', 'monthly_discount_percent')
    op.drop_column('pricing_configs', 'daily_base_price')
    op.drop_column('pricing_configs', 'anytime_surcharge_percent')
    op.drop_column('pricing_configs', 'weekly_base_price')
    op.drop_column('pricing_configs', 'monthly_base_price')
    op.drop_column('pricing_configs', 'weekly_discount_percent')
    op.drop_column('pricing_configs', 'daily_discount_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'reversion_snapshot',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('pricing_configs', 'anytime_monthly_price')
    op.drop_column('pricing_configs', 'anytime_weekly_price')
    op.drop_column('pricing_configs', 'anytime_daily_price')
    op.drop_column('pricing_configs', 'timeslot_monthly_price')
    op.drop_column('pricing_configs', 'timeslot_weekly_price')
    op.drop_column('pricing_configs', 'timeslot_daily_price')
    op.add_column('pricing_configs', sa.Column('daily_base_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('weekly_base_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('monthly_base_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('daily_discount_percent', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('weekly_discount_percent', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('monthly_discount_percent', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False))
    op.add_column('pricing_configs', sa.Column('anytime_surcharge_percent', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###
